name: Test windows-aarch64 availability


on:
  schedule:
    - cron: "30 16-23 * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-11-arm

    steps:
      - uses: actions/checkout@v4

      - name: Success
        run: echo Yay!
