name: Test windows-aarch64 availability


on:
  schedule:
    - cron: "15 2,3,4,5,6,7,8,9,10 * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-aarch64

    steps:
      - uses: actions/checkout@v4

      - name: Success
        run: echo Yay!
