name: Test windows-aarch64 availability


on:
  workflow_dispatch:
  push:

jobs:
  build:
    runs-on: ${{ matrix.os == 'windows-11-arm' && matrix.os || matrix.os'-latest' }}

    strategy:
      fail-fast: false
      matrix:
        os:
          - windows-11-arm
          - windows

    steps:
      - uses: actions/checkout@v4
      - uses: quansight-labs/setup-python@v5
        id: py
        with:
          python-version: |
            3.11
            3.12
            3.13
          allow-prereleases: true
          architecture: arm64

      - name: Print version and path
        run: | 
          echo ${{ steps.py.outputs.python-path }}
          echo ${{ steps.py.outputs.python-version }}
