name: Test windows-aarch64 availability


on:
  workflow_dispatch:
  push:

jobs:
  build:
    runs-on: ${{ 
        matrix.os == 'windows-11-arm' && matrix.os || 
        format('{0}-latest', matrix.os) 
      }}

    strategy:
      fail-fast: false
      matrix:
        os:
          - windows-11-arm
          - windows

    steps:
      - uses: actions/checkout@v4
      - uses: quansight-labs/setup-python@v5
        id: py
        with:
          python-version: |
            3.11
            3.12
            3.13
          allow-prereleases: true
          architecture: ${{ matrix.os == 'windows' && 'x64' || 'arm64' }}

      - name: Print Runner OS
        run: | 
          echo ${{ runner.os }}
          echo ${{ runner.arch }}
          echo ${{ runner.temp }}
      
      # - name: Install miniconda.
      #   uses: conda-incubator/setup-miniconda@v3 # https://github.com/conda-incubator/setup-miniconda.
      #   with:
      #     channels: conda-forge,defaults
      #     architecture: ${{ matrix.os == 'windows' && 'x64' || 'arm64' }}
      
      - name: Print version and path
        run: | 
          echo ${{ steps.py.outputs.python-path }}
          echo ${{ steps.py.outputs.python-version }}
