name: Test windows-aarch64 availability


on:
  workflow_dispatch:
  push:

jobs:
  build:
    runs-on: windows-11-arm

    steps:
      - uses: actions/checkout@v4
      - uses: quansight-labs/setup-python@v5
        id: py
        with:
          python-version: |
            3.11
            3.12
            3.13
          allow-prereleases: true
          architecture: $arm64

      - name: Print version and path
        run: | 
          echo ${{ steps.py.outputs.python-path }}
          echo ${{ steps.py.outputs.python-version }}
